# Generated by Django 5.2.7 on 2025-11-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0006_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-is_emergency', '-created_at']},
        ),
    ]
