# Generated by Django 5.2.7 on 2025-11-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0007_alter_servicerequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='schedule_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='schedule_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='schedule_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
