# Generated by Django 5.2.7 on 2025-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0008_servicerequest_schedule_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='labor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='materials_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='others_needed',
            field=models.BooleanField(default=False),
        ),
    ]
