# Generated by Django 5.2.7 on 2025-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0009_servicerequest_labor_servicerequest_materials_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachment',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='attachment_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
