# Generated by Django 5.2.7 on 2025-11-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0010_remove_servicerequest_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
