# Generated by Django 5.2.7 on 2025-11-19 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gso_accounts', '0003_employmentstatus_position_user_employment_status_and_more'),
        ('gso_requests', '0011_servicerequest_cancel_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('make_model', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_driver', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(blank=True, null=True)),
                ('driver_or_official', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requesting_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gso_accounts.department')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_po', to='gso_requests.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='FuelPurchaseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline - Unleaded', 'Gasoline - Unleaded'), ('Gasoline - Regular', 'Gasoline - Regular')], max_length=50)),
                ('qty_words', models.CharField(blank=True, max_length=255, null=True)),
                ('qty_figure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='gso_requests.fuelpurchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='MotorpoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(blank=True, null=True)),
                ('place_to_be_visited', models.CharField(blank=True, max_length=255, null=True)),
                ('trip_start', models.DateTimeField(blank=True, null=True)),
                ('trip_end', models.DateTimeField(blank=True, null=True)),
                ('itinerary', models.TextField(blank=True, null=True)),
                ('passengers_count', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Pick a user who is a driver (filter in forms/admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_assignments', to=settings.AUTH_USER_MODEL)),
                ('requesting_office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gso_accounts.department')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motorpool', to='gso_requests.servicerequest')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gso_requests.vehicle')),
            ],
        ),
    ]
