# Generated by Django 5.2.7 on 2025-11-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0012_vehicle_driverprofile_fuelpurchaseorder_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
