# Generated by Django 5.2.7 on 2025-11-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gso_requests', '0013_delete_driverprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorpoolrequest',
            name='driver',
        ),
    ]
